/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ClientDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/EngineerDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SignupScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/WelcomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/WorkerDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/styles/ClientDashboard.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/EngineerDashboard.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/LoginScreen.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/SignUpScreen.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/WorkerDashboard.styles`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ClientDashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/EngineerDashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SignupScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/WelcomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/WorkerDashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/ClientDashboard.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/EngineerDashboard.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/LoginScreen.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/SignUpScreen.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/WorkerDashboard.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/navigation/AppNavigator${`?${string}` | `#${string}` | ''}` | `/screens/ClientDashboard${`?${string}` | `#${string}` | ''}` | `/screens/EngineerDashboard${`?${string}` | `#${string}` | ''}` | `/screens/LoginScreen${`?${string}` | `#${string}` | ''}` | `/screens/SignupScreen${`?${string}` | `#${string}` | ''}` | `/screens/WelcomeScreen${`?${string}` | `#${string}` | ''}` | `/screens/WorkerDashboard${`?${string}` | `#${string}` | ''}` | `/styles/ClientDashboard.styles${`?${string}` | `#${string}` | ''}` | `/styles/EngineerDashboard.styles${`?${string}` | `#${string}` | ''}` | `/styles/LoginScreen.styles${`?${string}` | `#${string}` | ''}` | `/styles/SignUpScreen.styles${`?${string}` | `#${string}` | ''}` | `/styles/WorkerDashboard.styles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ClientDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/EngineerDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SignupScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/WelcomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/WorkerDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/styles/ClientDashboard.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/EngineerDashboard.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/LoginScreen.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/SignUpScreen.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/WorkerDashboard.styles`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
